---

name: Fatum Fatras
markdown: redcarpet
pygments: false
url: http://fatumfatras.com
exclude:
  - node_modules
  - src
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - package.json
  - README.md
